apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nwdaf-nbi-ml
  namespace: oai-5g-core
  labels:
    app: oai-nwdaf-nbi-ml
spec:
  selector:
    matchLabels:
      app: oai-nwdaf-nbi-ml
  template:
    metadata:
      labels:
        app: oai-nwdaf-nbi-ml
    spec:
      containers:
        - name: oai-nwdaf-nbi-ml
          image: production.imagehub/oai-nwdaf-nbi-ml:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: oai-nwdaf-nbi-ml
  namespace: oai-5g-core
  labels:
    app: oai-nwdaf-nbi-ml
spec:
  type: ClusterIP
  selector:
    app: oai-nwdaf-nbi-ml
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080