apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nwdaf-nbi-analytics
  namespace: oai-5g-core
  labels:
    app: oai-nwdaf-nbi-analytics
spec:
  selector:
    matchLabels:
      app: oai-nwdaf-nbi-analytics
  template:
    metadata:
      labels:
        app: oai-nwdaf-nbi-analytics
    spec:
      containers:
        - name: oai-nwdaf-nbi-analytics
          image: production.imagehub/oai-nwdaf-nbi-analytics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ENGINE_NUM_OF_UE_ROUTE
              value: /network_performance/num_of_ue
            - name: ENGINE_SESS_SUCC_RATIO_ROUTE
              value: /network_performance/sess_succ_ratio
            - name: ENGINE_UE_COMMUNICATION_ROUTE
              value: /ue_communication
            - name: ENGINE_UE_MOBILITY_ROUTE
              value: /ue_mobility
            - name: ENGINE_URI
              value: http://oai-nwdaf-engine:8080
---
apiVersion: v1
kind: Service
metadata:
  name: oai-nwdaf-nbi-analytics
  namespace: oai-5g-core
  labels:
    app: oai-nwdaf-nbi-analytics
spec:
  type: ClusterIP
  selector:
    app: oai-nwdaf-nbi-analytics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080