apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nwdaf-engine
  namespace: oai-5g-core
  labels:
    app: oai-nwdaf-engine
spec:
  selector:
    matchLabels:
      app: oai-nwdaf-engine
  template:
    metadata:
      labels:
        app: oai-nwdaf-engine
    spec:
      containers:
        - name: oai-nwdaf-engine
          image: production.imagehub/oai-nwdaf-engine:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: ENGINE_NUM_OF_UE_ROUTE
              value: /network_performance/num_of_ue
            - name: ENGINE_SESS_SUCC_RATIO_ROUTE
              value: /network_performance/sess_succ_ratio
            - name: ENGINE_UE_COMMUNICATION_ROUTE
              value: /ue_communication
            - name: ENGINE_UE_MOBILITY_ROUTE
              value: /ue_mobility
            - name: MONGODB_COLLECTION_NAME_AMF
              value: amf
            - name: MONGODB_COLLECTION_NAME_SMF
              value: smf
            - name: MONGODB_DATABASE_NAME
              value: testing
            - name: MONGODB_URI
              value: mongodb://oai-nwdaf-database:27017
---
apiVersion: v1
kind: Service
metadata:
  name: oai-nwdaf-engine
  namespace: oai-5g-core
  labels:
    app: oai-nwdaf-engine
spec:
  type: ClusterIP
  selector:
    app: oai-nwdaf-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
