/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

import (
	"encoding/json"
	"net/http"
	"os"
	"strings"
)

// NWDAFEventsSubscriptionsCollectionApiController binds http requests to an api service and writes the service results to the http response
type NWDAFEventsSubscriptionsCollectionApiController struct {
	service      NWDAFEventsSubscriptionsCollectionApiServicer
	errorHandler ErrorHandler
}

// NWDAFEventsSubscriptionsCollectionApiOption for how the controller is set up.
type NWDAFEventsSubscriptionsCollectionApiOption func(*NWDAFEventsSubscriptionsCollectionApiController)

// WithNWDAFEventsSubscriptionsCollectionApiErrorHandler inject ErrorHandler into controller
func WithNWDAFEventsSubscriptionsCollectionApiErrorHandler(h ErrorHandler) NWDAFEventsSubscriptionsCollectionApiOption {
	return func(c *NWDAFEventsSubscriptionsCollectionApiController) {
		c.errorHandler = h
	}
}

// NewNWDAFEventsSubscriptionsCollectionApiController creates a default api controller
func NewNWDAFEventsSubscriptionsCollectionApiController(s NWDAFEventsSubscriptionsCollectionApiServicer, opts ...NWDAFEventsSubscriptionsCollectionApiOption) Router {
	controller := &NWDAFEventsSubscriptionsCollectionApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the NWDAFEventsSubscriptionsCollectionApiController
func (c *NWDAFEventsSubscriptionsCollectionApiController) Routes() Routes {
	return Routes{
		{
			"CreateNWDAFEventsSubscription",
			strings.ToUpper("Post"),
			"/nnwdaf-eventssubscription/v1/subscriptions",
			c.CreateNWDAFEventsSubscription,
		},
	}
}

// CreateNWDAFEventsSubscription - Create a new Individual NWDAF Events Subscription
func (c *NWDAFEventsSubscriptionsCollectionApiController) CreateNWDAFEventsSubscription(w http.ResponseWriter, r *http.Request) {

	urlPath := os.Getenv("ENGINE_URI") + r.URL.Path

	nnwdafEventsSubscriptionParam := NnwdafEventsSubscription{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nnwdafEventsSubscriptionParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}

	result, err := c.service.CreateNWDAFEventsSubscription(r.Context(), nnwdafEventsSubscriptionParam, urlPath)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}
