/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"gitlab.eurecom.fr/development/oai-nwdaf/components/oai-nwdaf-nbi-events/pkg/events"
)

func main() {
	log.Printf("Server started")

	IndividualNWDAFEventSubscriptionTransferDocumentApiService := events.NewIndividualNWDAFEventSubscriptionTransferDocumentApiService()
	IndividualNWDAFEventSubscriptionTransferDocumentApiController := events.NewIndividualNWDAFEventSubscriptionTransferDocumentApiController(IndividualNWDAFEventSubscriptionTransferDocumentApiService)

	IndividualNWDAFEventsSubscriptionDocumentApiService := events.NewIndividualNWDAFEventsSubscriptionDocumentApiService()
	IndividualNWDAFEventsSubscriptionDocumentApiController := events.NewIndividualNWDAFEventsSubscriptionDocumentApiController(IndividualNWDAFEventsSubscriptionDocumentApiService)

	NWDAFEventSubscriptionTransfersCollectionApiService := events.NewNWDAFEventSubscriptionTransfersCollectionApiService()
	NWDAFEventSubscriptionTransfersCollectionApiController := events.NewNWDAFEventSubscriptionTransfersCollectionApiController(NWDAFEventSubscriptionTransfersCollectionApiService)

	NWDAFEventsSubscriptionsCollectionApiService := events.NewNWDAFEventsSubscriptionsCollectionApiService()
	NWDAFEventsSubscriptionsCollectionApiController := events.NewNWDAFEventsSubscriptionsCollectionApiController(NWDAFEventsSubscriptionsCollectionApiService)

	router := events.NewRouter(IndividualNWDAFEventSubscriptionTransferDocumentApiController, IndividualNWDAFEventsSubscriptionDocumentApiController, NWDAFEventSubscriptionTransfersCollectionApiController, NWDAFEventsSubscriptionsCollectionApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
