ARG BUILD_IMAGE=golang:1.19-alpine
ARG TARGET_IMAGE=ubuntu:focal

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------

FROM $BUILD_IMAGE AS oai-nwdaf-nbi-events-build

WORKDIR /oai/nwdaf/nbi-events

ENV CGO_ENABLED=0

COPY go.* ./
RUN go mod download

COPY . ./
RUN go build -o bin/oai-nwdaf-nbi-events cmd/oai-nwdaf-nbi-events/main.go

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------

FROM $TARGET_IMAGE AS oai-nwdaf-nbi-events

RUN apt-get update && apt-cache search net-tools &&  apt-get install --yes net-tools 

COPY --from=oai-nwdaf-nbi-events-build /oai/nwdaf/nbi-events/bin/oai-nwdaf-nbi-events ./

EXPOSE 8080/tcp
ENTRYPOINT ["./oai-nwdaf-nbi-events"]
