ARG BUILD_IMAGE=golang:1.19-alpine
ARG TARGET_IMAGE=ubuntu:focal

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------

FROM $BUILD_IMAGE AS oai-nwdaf-nbi-ml-build

WORKDIR /oai/nwdaf/nbi-ml

ENV CGO_ENABLED=0

COPY go.* ./
RUN go mod download

COPY . ./
RUN go build -o bin/oai-nwdaf-nbi-ml cmd/oai-nwdaf-nbi-ml/main.go

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------

FROM $TARGET_IMAGE AS oai-nwdaf-nbi-ml

RUN apt-get update && apt-cache search net-tools &&  apt-get install --yes net-tools 

COPY --from=oai-nwdaf-nbi-ml-build /oai/nwdaf/nbi-ml/bin/oai-nwdaf-nbi-ml ./

EXPOSE 8080/tcp
ENTRYPOINT ["./oai-nwdaf-nbi-ml"]
